const SOURCE={...LEGACY.sources,...EXTRA_SOURCES};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const oldAge={newborn:'week',infant:'young',middle:'middle',older:'older',toddler:'toddler'};
const query=new URLSearchParams(location.hash.replace(/^#/,''));
let oldMatch=location.hash.match(/^#age-(.+)$/);
const state={age:query.get('age')||oldAge[oldMatch?.[1]]||document.documentElement.dataset.careAge||'week',topic:query.get('topic')||document.documentElement.dataset.careTopic||'feeding',method:query.get('method')||document.documentElement.dataset.careMethod||'breast'};
if(!AGES.some(a=>a.id===state.age))state.age='week';if(!TOPICS.some(t=>t.id===state.topic))state.topic='feeding';if(!['breast','formula','expressed','mixed'].includes(state.method))state.method='breast';
let lastVideoFocus=null,noticeTimer,videoFallbackTimer,indexing=false;
function refs(ids){return `<div class="refs">${[...new Set(ids)].filter(id=>SOURCE[id]).map(id=>`<a href="${esc(SOURCE[id].url)}" target="_blank" rel="noopener noreferrer">${esc(SOURCE[id].title)}</a>`).join('')}</div>`}
function steps(items){return `<ol class="steps">${items.map(([title,text])=>`<li><div><strong>${esc(title)}</strong><br>${esc(text)}</div></li>`).join('')}</ol>`}
function videoButton(id,text='看中文图解短片'){return VIDEOS[id]?`<button class="play-button" data-video="${id}"><span class="play-icon" aria-hidden="true">▶</span>${esc(text)}</button>`:''}
function photo(id){if(indexing)return '';const a=ASSETS[id];return a?`<div class="lesson-visual"><img src="${a.data}" alt="${esc(a.alt)}" width="${a.width}" height="${a.height}"><p class="image-caption">${esc(a.caption)}<br><a href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">图片来源：香港卫生署家庭健康服务</a></p></div>`:''}
function lesson(key){const l=LESSONS[key];return `<section class="lesson" id="lesson-${key}">${photo(key==='bottle'?'bottleHold':l.image)}<div class="lesson-body"><p class="eyebrow">跟着做 · ${l.steps.length}个步骤</p><h3>${esc(l.title)}</h3>${steps(l.steps)}${key==='bottle'?`<details class="angle-photo"><summary>展开奶瓶角度近照</summary>${photo('bottle')}</details>`:''}${videoButton(l.video)}${refs(l.refs)}</div></section>`}
function card(title,items,source=[],note=''){return `<article class="card"><h3>${esc(title)}</h3><ul>${items.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${note?`<p class="micro-note">${esc(note)}</p>`:''}${refs(source)}</article>`}
function faq(items){return `<section class="faq"><h3 class="quick-title">遇到这些情况</h3>${items.map(([q,a])=>`<details><summary>${esc(q)}</summary><div class="answer">${esc(a)}</div></details>`).join('')}</section>`}
function stats(items){return `<div class="stats">${items.map(([big,label,note])=>`<div class="stat"><b>${esc(big)}</b><span>${esc(label)}</span><small>${esc(note)}</small></div>`).join('')}</div>`}
function age(){return AGES.find(a=>a.id===state.age)}
function legacyCards(topic){const s=LEGACY.stages.find(s=>s.id===age().legacy);let cs=s.cards;if(topic==='feeding')cs=cs.filter(c=>/吃|饮食|配方/.test(c.tag));if(topic==='sleep')cs=cs.filter(c=>/睡|互动|安抚/.test(c.tag));if(topic==='care')cs=cs.filter(c=>/清洁|牙齿|安全/.test(c.tag));return `<div class="grid">${cs.map(c=>card(c.title,c.items,[c.source],c.avoid)).join('')}</div>`}
function milkReference(){
 const isWeek=state.age==='week',isMonth=state.age==='month';
 const highlighted=isWeek?[['30–60 mL','最初几天每次可先提供','只适用于全配方奶，起始参考'],['约2–3小时','常见喂奶间隔','看见饥饿信号可提前'],['不必喝完','看吃饱信号停下','不把参考量当最低限额']]:isMonth?[['60–90 mL','随后数周常见每次参考','接近满月可逐渐增加'],['约3–4小时','常见间隔，会有变化','不为凑间隔延迟喂奶'],['看趋势','尿布、吞咽与随访体重','一顿多一顿少并不罕见']]:state.age==='young'?[['按需调整','2、3个月没有统一每顿量','不按月龄自动加量'],['接近满月','90–120 mL/次仅供该节点参考','不是整个1–3个月固定量'],['看整体','有效进食、尿布和生长','担心摄入时请儿科评估']]:[['不提前套量','4–5个月不套6个月参考','按饥饱信号逐渐调整'],['约6个月','常见180–240 mL/次','只对应6个月左右全配方奶'],['看整体','尿布、精神和体重趋势','不把范围上端相乘当目标']];
 return `<div class="notice"><strong>这里只是全配方奶参考。</strong>不是每顿必须喝完的目标；<strong>混合喂养的每次补喂量和全天补喂量，都不能套用这张表。</strong>补多少要结合亲喂是否有效、尿布和体重，由儿科或哺乳专业人员协助确认。早产、黄疸明显或生长不理想，请按个体方案。</div>${stats(highlighted)}<details class="milk-table faq"><summary>展开奶量参考表与适用条件</summary><div class="table-wrap"><table><caption>足月、一般健康宝宝的全配方奶粗略参考</caption><thead><tr><th>阶段</th><th>每次参考</th><th>如何使用</th></tr></thead><tbody><tr><th>最初几天</th><td><strong>30–60 mL</strong></td><td>CDC建议可先提供这个量，约每2–3小时，按饥饱信号调整。</td></tr><tr><th>随后数周</th><td><strong>60–90 mL</strong></td><td>香港卫生署列为常见参考，通常约3–4小时，宝宝也可能更频繁索食。</td></tr><tr><th>接近满月</th><td><strong>90–120 mL</strong></td><td>AAP描述为第一个月内逐渐增加到的量，不要求每个宝宝达到。</td></tr><tr><th>约6个月</th><td><strong>180–240 mL</strong></td><td>AAP描述常见每次范围，通常每天4–5次；不要将上限相乘作为全天目标。</td></tr></tbody></table></div><p class="micro-note">AAP另提示通常全天配方奶平均不超过约960mL。若持续明显高于或低于常见参考，联系儿科评估；不要自行限奶或为了凑量强喂。2–5个月不按表格做线性外推。</p>${refs(['formulaAmount','fhsBottle','aapAmount'])}</details>`;
}
function mixedFeeding(){return `<section class="mixed-intro" id="mixed-guide"><div class="notice"><strong>母乳＋配方奶，先看宝宝怎么吃。</strong>每次和全天补喂量都不能直接套用全配方奶表。补多少要结合亲喂时的吞咽、尿布和体重，由儿科或哺乳专业人员协助确认。</div><div class="grid">${card('先看吃奶表现',['亲喂时留意：脸颊圆，能看到或听到吞咽。','持续疼痛、反复滑脱或听到咂嘴声，请哺乳专业人员看一次完整喂奶。','频繁找奶不自动等于奶不够，也不要只靠一顿喝了多少判断。'],['latch','enoughMilk'])}${card('再看尿布和生长',['湿尿布按宝宝日龄观察，看是否比平日明显减少。','便便次数不直接套母乳栏；同时看是否柔软、吃奶和生长是否正常。','最初约6周便次明显减少，要联系医护检查进食。'],['nappy','enoughMilk'])}</div><div class="mixed-actions"><button class="play-button secondary" data-jump="lesson-breast">看亲喂与吞咽</button><button class="play-button secondary" data-go-topic="diaper" data-go-target="nappy-count">看这个年龄的尿布</button><button class="play-button secondary" data-jump="medical">何时求助</button></div><div class="gentle"><strong>需要补喂时，也给宝宝暂停的机会。</strong>瓶喂按饥饱信号进行，停吸、转头或推开奶瓶时先暂停，不强迫喝完。早产、低出生体重、黄疸明显或生长不理想，请按个体方案。</div></section>`;}
function feeding(){
 if(['older','toddler'].includes(state.age))return `<div class="notice">${esc(age().feedingNote)}</div>${legacyCards('feeding')}${card('把防噎做在每一餐',['坐稳、坐直，成人全程在旁，不边跑边吃。','葡萄等圆形食物纵向切成四小块；坚硬食物煮软或切细。','不提供整颗坚果、硬糖、爆米花。坚果酱薄涂或拌入，不整勺喂。'],['choking'])}<div class="gentle">食量会有波动，尽量看一段时间的摄入与生长，不把每一餐变成比赛。</div>`;
 const methodBar=`<div class="method-tabs" role="group" aria-label="选择喂养方式"><button class="method-tab" data-method="breast" aria-pressed="${state.method==='breast'}">母乳亲喂</button><button class="method-tab" data-method="formula" aria-pressed="${state.method==='formula'}">配方奶</button><button class="method-tab" data-method="mixed" aria-pressed="${state.method==='mixed'}">母乳＋配方奶<span>混合喂养</span></button><button class="method-tab" data-method="expressed" aria-pressed="${state.method==='expressed'}">母乳瓶喂</button></div>`;
 let top=state.method==='mixed'?mixedFeeding():state.method==='formula'?milkReference():state.method==='breast'?`${stats([[['week','month'].includes(state.age)?'8–12次':'按需亲喂',['week','month'].includes(state.age)?'新生儿常见24小时亲喂频次':'月龄增长后频次因人而异','并非所有月龄的固定任务'],['不按mL','亲喂看有效进食','观察吞咽、尿布、体重'],['按需要','找奶时回应，吃饱时停','频繁索食不自动等于没奶']])}<p class="micro-note">8–12次主要用于新生儿建立喂养的参考；月龄增长后频次可变化。混合喂养也应结合有效进食评估。</p>`:`<div class="notice">母乳瓶喂同样看饥饱信号，采用下面的回应式瓶喂步骤。不直接套用全配方奶的全天参考量，也不要求喝完一瓶。</div>${stats([['小量分装','需要时再追加','减少浪费与强喂'],['暂停休息','看宝宝的吸吮节奏','转头、停吸时休息'],['看整体','有效吞咽、尿布和体重','不是只看瓶中少了多少']])}`;
 return `${methodBar}${top}${state.method==='mixed'?lesson('breast')+lesson('bottle'):lesson(state.method==='breast'?'breast':'bottle')}<div class="grid">${card('饿了，通常先有这些信号',['张嘴、转头寻找乳头，舔嘴或手靠近嘴。','哭往往是较晚信号；先轻柔安抚，再尝试喂。','需要叫醒喂奶的情况，按出院或儿科方案执行。'],['feeding','fhsBottle'])}${card('吃饱或需要暂停，看这里',['吸吮变慢、松开奶嘴或乳头，转头、闭嘴。','推开奶瓶、奶从嘴角流出时先暂停，不追着喂。','抱着喂并观察呼吸，不用毛巾或支架垫瓶独自喂。'],['fhsBottle'])}</div><h3 class="quick-title">喂奶中途或之后，试试这样拍嗝</h3>${lesson('burping')}${faq([['拍不出嗝，是不是没拍好？','不是每次都要拍出嗝。轻试几分钟、宝宝舒服即可；不要为了“必须响一声”用力或一直拍。'],['吐一点奶，需要侧睡或垫高吗？','不需要。少量从嘴角流出、精神和生长正常很常见；按饱足信号停喂，清醒看护下可竖抱约10–20分钟。睡觉仍平躺仰卧，不能侧睡或抬高床头。'],['奶量少于表格，就一定不够吗？','不能只靠一顿或一个数字判断。观察能否有效吞咽、尿布是否明显减少、孩子是否精神正常以及随访体重。持续吃奶少、难唤醒或尿少，应联系儿科，不能仅在家继续追量。'],['乳头一直疼，应该忍着吗？','持续疼痛、破损或反复含接不稳，应尽快找助产士或哺乳专业人员看一次完整喂奶过程；不要只靠强行延长喂奶时间解决。']])}<div class="notice danger"><strong>绿色／黄绿色、带血或喷射性呕吐，明显拒奶、腹胀、留不住奶或精神差，需要医疗评估。</strong>呼吸异常、难唤醒时立即呼叫急救。<a href="#medical">查看就医提示</a></div>${refs(['fhsBottle','reflux'])}`;
}
function sleep(){
 const toddler=state.age==='toddler',young=!['older','toddler'].includes(state.age);
 const routine=toddler?[['先放慢节奏','结束活跃游戏，刷牙和清洁后，逐渐降低灯光与声音。'],['重复简单流程','读一本短书、唱一首歌、说晚安。顺序可预期，不需要复杂仪式。'],['回应情绪，保持边界','孩子害怕或不愿分开时，用简单的话安慰。可以让孩子在两本睡前书中选一本。'],['检查床和周边','使用适龄睡床，防坠落和夹伤；床边远离窗户、窗帘绳、电线和可攀爬物。']]:SLEEP_STEPS;
 const checks=toddler?['适龄睡床，防坠落夹伤','床边无窗帘绳或电线','睡前活动安静、可预期','大人用温和一致的方式回应']:['仰卧放下','独立的婴儿床或睡篮','床垫平坦、坚实','无枕头、玩偶、床围软垫','无松散被褥、定位枕或斜垫',state.age==='older'?'会翻身后仍每次仰卧放下':'至少前6个月同室不同床'];
 return `<div class="notice">${esc(age().sleepNote)}</div><section id="sleep-steps" aria-label="安抚入睡步骤"><h3 class="quick-title">${toddler?'幼儿睡前，可以这样安排':'夜里醒了，可以按这个顺序试'}</h3><div class="routine">${routine.map(([t,p],i)=>`<article class="routine-step"><span class="routine-number">${i+1}</span><h3>${esc(t)}</h3><p>${esc(p)}</p></article>`).join('')}</div></section><section class="card" id="sleep-safe"><div class="card-top"><h3>最后一步：检查睡眠环境</h3><span class="label">${toddler?'1–3岁适用':'一岁以内适用'}</span></div><ul class="sleep-checks">${checks.map(c=>`<li>${esc(c)}</li>`).join('')}</ul>${toddler?refs(['sleepHelp','safety','parenting']):`<p class="micro-note">已经能自主双向翻身的宝宝，不必反复翻回；但每次开始睡眠时仍仰卧放下。出现尝试翻身的迹象即停止襁褓包裹。</p>${refs(['sleep','fhsSleep'])}<div class="video-actions"><a class="play-button secondary" href="${SOURCE.safeSleepVideo.url}" target="_blank" rel="noopener noreferrer">▶ 看官方安全睡眠短片</a><span class="micro-note">2024年短片 · 打开官方页面观看</span></div>`}</section><div id="sleep-faq">${faq(young?[['一放下就醒，还能再抱吗？','可以。新生儿需要抱哄很常见，不代表被“惯坏”。先观察是否真的醒了；醒来哭或有需求就回应，必要时再抱起安抚。成人快睡着时，先把宝宝放回安全小床。'],['闭着眼哼唧、扭动，要马上抱起来吗？','这可能是浅睡中的活动，可在旁短暂观察呼吸和状态。不是固定让宝宝哭几分钟；真正醒来哭、有饥饿信号或不舒服时及时回应。'],['能规定几个月必须睡整觉、断夜奶吗？','不能仅按月龄要求。小月龄夜醒吃奶常见；是否需要夜间叫醒喂奶、能否延长间隔，应结合体重、黄疸、早产情况和医生建议。'],['已经很累、快忍不住了怎么办？','先把宝宝仰卧放进安全空床，自己短暂离开平复，尽快找可信赖的人接手。绝不摇晃宝宝，也不抱着在沙发或扶手椅上睡。']]:[['睡前流程怎么做才简单？','重复几件安静的小事即可，例如清洁、刷牙、读短故事、调暗灯光，再入床。保持温和、可预期，不需要复杂仪式。'],['已经会的能力退步，或睡眠变化伴身体不适？','及时与儿科讨论，尤其伴异常嗜睡、发热、呼吸异常、进食减少时。不要只当作“睡眠倒退”。']])}</div><div class="gentle"><strong>宝宝不用一次学会，大人也不用。</strong>安全、回应需求和有人分担，比完成一个睡眠时间表更重要。</div>${refs(['crying','sleepHelp'])}`;
}

function diaper(){
 const early=['week','month','young','middle'].includes(state.age);
 return `<div class="notice"><strong>先分清：湿尿布数 ≠ 排尿次数 ≠ 换尿布次数。</strong>一片可能有不止一次尿；混合大小便的尿布，只要明显湿，也可计入。</div><div class="notice muted"><strong>混合喂养怎么用这张表？</strong>湿尿布按日龄观察；便次不要直接套母乳栏，也不自行设定必须每天几次。看便是否软、吃奶与生长是否正常、是否比平日明显减少。最初约6周便次明显减少，应联系医护检查有效进食。</div>${early?`<div id="nappy-count" class="notice muted"><strong>${esc(age().label)}先看这里：</strong>${state.age==='week'?'按具体日龄看下表；第5天起通常至少6片明显湿尿布。':state.age==='month'?'24小时通常至少约6片明显湿尿布。母乳宝宝通常每天至少2次软便；混合或配方喂养不套母乳便次。':'留意湿尿布是否明显减少。约6周前便次明显减少要检查进食；6周后软便且状态、生长正常，母乳宝宝可几天一次。'}</div><div class="table-wrap"><table><caption>小月龄尿布观察表 · 按24小时看</caption><thead><tr><th>日龄／月龄</th><th>湿尿布参考</th><th>便便变化</th></tr></thead><tbody>${NAPPY_ROWS.map(r=>`<tr class="${r.ids.includes(state.age)?'active-row':''}"><th>${r.age}</th><td><strong>${r.wet}</strong></td><td>${r.poo}</td></tr>`).join('')}</tbody></table></div><p class="micro-note">表中的早期便次主要指母乳喂养。配方奶宝宝的便可能较稠、较深，次数可不同，不套用母乳便次。香港卫生署对第5天起写5–6片；NHS写至少6片，本页用“通常至少6片”作为观察参考，不凭少一片诊断脱水。</p>${refs(['fhsBreast','fhsBottle','enoughMilk','nappy'])}`:`<div class="grid" id="nappy-count">${card('更大宝宝不按新生儿表打分',['辅食、饮食变化会影响便便颜色、气味和次数。','与孩子平常比较：便是否干硬、排便是否疼、尿是否明显减少。','发热、明显水样便、血便、精神差或脱水信号应联系医生。'],['nappy','constipation'])}${card('排便少，不自动等于便秘',['便便柔软、排出不痛，比“每天必须一次”更重要。','干硬小球、排便疼痛更提示便秘，应咨询儿科。','不自行刺激肛门、灌肠或使用泻药。'],['constipation'])}</div>`}<div class="freq-strip"><div class="freq-item"><strong>淡黄／清亮</strong><p>常见尿色；持续深色、明显尿少需要关注。</p></div><div class="freq-item"><strong>约45 mL水</strong><p>可倒入一片干净尿布，感受“明显湿”的重量。</p></div><div class="freq-item"><strong>自然光拍照</strong><p>拿不准颜色时保留照片或尿布，请医护判断。</p></div></div><h3 class="quick-title" id="poo-colors">便便颜色速查</h3><p class="micro-note">以下只是颜色示意，不是诊断色卡。屏幕、光线和尿布吸收都会改变颜色；还要看日龄、质地、精神与吃奶。</p><div class="color-grid">${COLORS.map(c=>`<article class="color-card ${c.alert?'alert':''}"><div class="color-swatch" style="--swatch:${c.hex}" aria-hidden="true"><span>${esc(c.tag)}</span></div><div class="color-body"><h3>${esc(c.name)}</h3><p>${esc(c.text)}</p></div></article>`).join('')}</div>${refs(['nappy','jaundice','bloodStool','pooPhotos'])}<div class="video-actions">${videoButton('diaper','看换尿布图解')}<a href="${SOURCE.pooPhotos.url}" target="_blank" rel="noopener noreferrer">查看真实尿布照片（NCT · 英文）</a></div><div id="diaper-questions">${faq([['尿布上有粉橙色、砖红色粉末，是血吗？','生后最初几天可能是尿酸盐结晶。超过最初几天仍反复出现，或同时尿少、吃奶不足，要联系医护检查摄入。拿不准是否出血时，保留照片或尿布，不自行认定。'],['母乳宝宝几天不拉，是“攒肚”吗？','要看年龄。最初约6周，便次明显减少应先检查有效喂养；约6周后，便仍软、吃奶和生长正常的母乳宝宝可几天一次。不能把所有小月龄不排便都叫正常“攒肚”。'],['便便稀、带小颗粒，是腹泻吗？','母乳便本来可能较稀、有细颗粒。突然比平常明显增多、呈水样，尤其伴发热、拒奶、尿少或精神差，需要医疗评估。'],['今天湿尿布明显少，下一顿多冲一点就好吗？','不要只靠多冲奶解决，也不要自行加浓或稀释奶粉。明显少于平日应及时联系儿科评估喂养；长时间无尿、难唤醒、发热或拒奶时要立即获得医疗帮助。']])}</div><div class="notice danger">白／灰白便、便血、胎便期后的黑色柏油样便，不只在家观察。伴精神差、腹痛、反复呕吐或明显尿少时，及时就医。</div>`;
}
function care(){if(state.age==='toddler')return `${legacyCards('care')}<h3 class="quick-title">幼儿日常照护</h3><div class="grid">${card('刷牙和清洁，成人仍要帮忙',['每天两次含氟牙膏刷牙：未满3岁薄薄米粒量，满3岁起豌豆量。','洗澡时用品先备齐、成人全程在旁；离开时把孩子一同带走。','仍用尿布的孩子及时更换、轻柔清洁并拍干，女宝宝从前往后擦。'],['teeth','safety','nappy'])}${card('出门与家里，先做好防护',['固定家具和电视，窗边不放可攀爬家具。','药品、清洁剂、纽扣电池和磁铁上锁放好。','使用适龄、符合当地标准的儿童安全座椅；在水边不让年长孩子替代成人看护。'],['safety'])}</div>`;return `${legacyCards('care')}<h3 class="quick-title">换尿布，一次准备好</h3><div class="routine">${[['先备齐','干净尿布、温水或合适湿巾、干毛巾放在手边，先洗手。'],['轻柔清洁','脏了及时换；女宝宝从前往后擦，皮肤褶皱也轻轻清洁。'],['拍干，再包好','保持干爽，松紧合适，脐带未脱落时上缘避开脐部。'],['全程在旁','地面垫子更安全。高处一手护住，绝不独自留下；结束后洗手。']].map(([t,p],i)=>`<article class="routine-step"><span class="routine-number">${i+1}</span><h3>${t}</h3><p>${p}</p></article>`).join('')}</div>${videoButton('diaper','看换尿布图解短片')}<h3 class="quick-title">冲奶、洗澡和清洁的小提醒</h3><div class="grid">${card('冲调配方奶：比例、温度与时限',['先量水，再按包装使用准确平勺奶粉；不加浓、不随意稀释。','奶粉并非无菌。未满2个月、早产或免疫功能较弱的宝宝，需要额外安全措施；请向医护确认冲调方法或即饮配方奶选择。','冲好后2小时内、开始喂后1小时内用完，以较早者为准；不马上喂就立即冷藏，24小时内用完，喝剩的丢弃。','冲调温度与消毒方式参考当地卫生指导及适用产品；不要用微波炉加热奶。'],['formula'])}${card(['week','month'].includes(state.age)?'洗澡与脐带：温和、干爽、一直在旁':'洗澡与清洁：温和、一直在旁',['水温先确认适宜，用品提前备齐；成人始终留在伸手可及处。','水再浅也不独自留下；浴盆座椅或哥哥姐姐不能替代成人。',...(['week','month'].includes(state.age)?['脐带保持清洁干燥、不拉扯；有特殊医嘱时按医嘱，不自行撒粉或涂偏方。','脐周红肿扩散、脓液、发热或宝宝状态差，应尽快就医。']:['轻柔清洁皮肤褶皱并拍干；不要大力擦洗皮肤。','已有牙齿就开始每天两次刷牙，由成人帮助。'])],['cord','safety'])}</div><div class="gentle"><strong>交给家人时，一起看同一张卡。</strong>把喂奶是否顺利、湿尿布是否减少、有没有异常告诉接手的人，比只交代“几点喝了多少”更完整。</div>`}
function duration(sec){return sec?`${Math.floor(sec/60)}分${sec%60?String(sec%60).padStart(2,'0')+'秒':''}`:'短片'}
function mediaUrl(relative){return new URL(relative,document.documentElement.dataset.careMediaBase||document.baseURI).href}
function videoCard(v){const a=indexing?null:ASSETS[v.image];return `<article class="video-card"><button class="video-thumb" data-video="${v.id}" aria-label="播放${esc(v.title)}中文图解">${a?`<img src="${a.data}" alt="${esc(a.alt)}" loading="lazy">`:`<span class="video-fallback-title">${esc(v.title)}</span>`}<span class="play-overlay"><span aria-hidden="true">▶</span></span></button><div class="video-meta"><div class="video-badges"><span>${duration(v.clipDuration)}</span><span>中文图解 · 无配音</span></div><h3>${esc(v.title)}</h3><p>本站制作的逐步图解，可直接播放。<br>弹窗中另有官方真人示范入口。</p><div class="refs"><a href="${esc(v.sourceUrl)}" target="_blank" rel="noopener noreferrer">官方原页／文字稿</a></div></div></article>`}
function videos(){return `<div class="notice muted"><strong>先看本站中文图解，再按需要看官方真人示范。</strong>四段图解使用专业照片或步骤图形，没有配音，也不是连续真人动作视频。图解直接由本站提供；官方真人视频使用YouTube，部分网络可能无法播放。含接、换尿布另有NHS英语示范。</div><div class="video-grid">${Object.values(VIDEOS).map(videoCard).join('')}</div><section class="card"><h3>安全睡眠：2024年官方短片</h3><p>查看仰卧、同室独立婴儿床、睡面无杂物与松散被褥的示范。</p><div class="video-actions"><a class="play-button secondary" href="${SOURCE.safeSleepVideo.url}" target="_blank" rel="noopener noreferrer">▶ 打开官方页面观看</a></div><p class="micro-note">香港卫生署／新闻处。该片在官方页面观看；“哄睡与安抚”另有可离线查看的中文步骤。</p><button class="text-button" data-topic="sleep">查看哄睡与安抚步骤</button></section>`}
function quickJumps(){const links=state.topic==='diaper'?[['nappy-count',['older','toddler'].includes(state.age)?'当期观察要点':'当期尿布次数'],['poo-colors','便便颜色'],['diaper-questions','几天不拉／尿少']]:state.topic==='sleep'?[['sleep-steps','安抚步骤'],['sleep-safe','睡眠安全'],['sleep-faq','常见问题']]:state.topic==='feeding'&&!['older','toddler'].includes(state.age)?[[state.method==='mixed'?'mixed-guide':state.method==='breast'?'lesson-breast':'lesson-bottle',state.method==='mixed'?'混合喂养怎么观察':'喂奶姿势'],['lesson-burping','拍嗝与吐奶']]:[];return links.length?`<nav class="quick-jumps" aria-label="本页快捷查找">${links.map(([id,t])=>`<a href="#${id}">${t}</a>`).join('')}</nav>`:'';}
function render(sync=true){
 document.documentElement.dataset.careAge=state.age;document.documentElement.dataset.careTopic=state.topic;document.documentElement.dataset.careMethod=state.method;
 $('#age-tabs').innerHTML=AGES.map(a=>`<button role="tab" aria-selected="${a.id===state.age}" aria-controls="content" class="age-tab" data-age="${a.id}" tabindex="${a.id===state.age?0:-1}">${esc(a.label)}</button>`).join('');
 $('#topic-tabs').innerHTML=TOPICS.map((t,i)=>`<button class="topic-tab" data-topic="${t.id}" ${t.id===state.topic?'aria-current="page"':''}><span class="topic-icon" aria-hidden="true">0${i+1}</span>${esc(t.id==='feeding'&&['older','toddler'].includes(state.age)?'吃饭与喂养':t.label)}</button>`).join('');
 const t=TOPICS.find(t=>t.id===state.topic),heading=t.id==='feeding'&&['older','toddler'].includes(state.age)?'吃饭与喂养':t.title;
 const descriptions={feeding:age().feedingNote,sleep:age().sleepNote,diaper:'先按年龄看次数，再结合颜色、质地和宝宝状态。',care:'准备在前，轻柔操作，有疑问时及时求助。',videos:'中文图解直接播放，官方真人视频可另选。'};
 $('#content').innerHTML=`<div class="section-heading"><div><h2>${esc(heading)}</h2><p>${esc(descriptions[state.topic])}</p></div><span class="age-pill">${esc(age().label)}</span></div><p class="print-scope">小小长大 · ${esc(age().label)} · ${esc(t.label)} · ${state.topic==='feeding'&&!['older','toddler'].includes(state.age)?esc({breast:'母乳亲喂',formula:'全配方奶参考',expressed:'母乳瓶喂',mixed:'母乳＋配方奶（混合喂养）'}[state.method]):''}<br>适用于一般健康足月儿的家庭照护。早产、低出生体重、基础疾病、黄疸明显或生长喂养困难者按医嘱；本页不能替代儿科评估。资料核对：2026年10月4日。视频需联网。图片来源：香港卫生署家庭健康服务。</p>`+quickJumps()+({feeding,sleep,diaper,care,videos}[state.topic]());
 tagSearchBlocks($('#content'));
 if(sync){try{history.replaceState(null,'',`#age=${state.age}&topic=${state.topic}&method=${state.method}`)}catch(e){}}
}
function update(part,focusKey){Object.assign(state,part);render();if(focusKey)document.querySelector(focusKey)?.focus()}
document.addEventListener('click',e=>{const a=e.target.closest('[data-age]');const t=e.target.closest('[data-topic]');const m=e.target.closest('[data-method]');const v=e.target.closest('[data-video]');if(a&&a.tagName==='BUTTON')update({age:a.dataset.age},`[data-age="${a.dataset.age}"]`);else if(t&&t.tagName==='BUTTON')update({topic:t.dataset.topic},`#topic-tabs [data-topic="${t.dataset.topic}"]`);else if(m)update({method:m.dataset.method},`[data-method="${m.dataset.method}"]`);else if(v)openVideo(v.dataset.video,v)});
$('#age-tabs').addEventListener('keydown',e=>{let i=AGES.findIndex(a=>a.id===state.age),next;if(['ArrowRight','ArrowDown'].includes(e.key))next=(i+1)%AGES.length;if(['ArrowLeft','ArrowUp'].includes(e.key))next=(i-1+AGES.length)%AGES.length;if(e.key==='Home')next=0;if(e.key==='End')next=AGES.length-1;if(next!==undefined){e.preventDefault();update({age:AGES[next].id},`[data-age="${AGES[next].id}"]`)}});
function showVideoHelp(message){const box=$('#video-state');if(box){box.hidden=false;box.textContent=message}}
function playCareVideo(id,kind){
 const v=VIDEOS[id];if(!v)return;clearTimeout(videoFallbackTimer);const box=$('#video-state');box.hidden=true;
 $$('#video-content [data-player-kind]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.playerKind===kind)));
 const player=$('#care-player');player.classList.toggle('native-player',kind==='local');
 if(kind==='local'){
  player.innerHTML=`<video controls playsinline preload="metadata" aria-label="${esc(v.title)}中文图解，无配音" poster="${esc(mediaUrl(v.clipPoster))}"><source src="${esc(mediaUrl(v.clipPath))}" type="video/mp4"><track kind="captions" src="${esc(mediaUrl(v.clipCaptions))}" srclang="zh" label="中文步骤">浏览器不支持此视频，请点上方“阅读大字步骤”。</video>`;
  $('#player-description').textContent='本站中文图解 · 无配音 · '+duration(v.clipDuration)+'。使用照片或步骤图形讲解，不是连续真人动作视频。';
  const video=player.querySelector('video');
  video.addEventListener('playing',()=>{clearTimeout(videoFallbackTimer);box.hidden=true});
  video.addEventListener('error',()=>{clearTimeout(videoFallbackTimer);showVideoHelp('图解暂时未能加载。请检查网络，或先点上方“阅读大字步骤”。')});
  videoFallbackTimer=setTimeout(()=>{if(video.readyState<3)showVideoHelp('图解还在加载，请检查网络或先点上方“阅读大字步骤”。')},12000);
  video.play().catch(()=>showVideoHelp('请点画面中的播放按钮开始；也可以点上方“阅读大字步骤”。'));
 }else{
  const origin=location.protocol==='http:'||location.protocol==='https:'?`&origin=${encodeURIComponent(location.origin)}`:'';
  player.innerHTML=`<iframe src="${esc(v.embedUrl)}?rel=0&enablejsapi=1${origin}" title="${esc(v.title)}官方真人视频" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; fullscreen" allowfullscreen referrerpolicy="strict-origin-when-cross-origin"></iframe>`;
  $('#player-description').textContent=v.provider+' · '+v.language+' · '+duration(v.durationSeconds)+'。需要能够访问YouTube的网络。';
  const frame=player.querySelector('iframe');frame.addEventListener('load',()=>frame.contentWindow?.postMessage(JSON.stringify({event:'listening',id:'care-video'}),'https://www.youtube-nocookie.com'));
  videoFallbackTimer=setTimeout(()=>showVideoHelp('官方真人视频还没有开始播放，可能受YouTube或当前网络限制。可切回“本站中文图解”继续观看。'),12000);
 }
}
function openVideo(id,trigger){
 const v=VIDEOS[id];if(!v)return;lastVideoFocus=trigger;$('#video-title').textContent=v.title;
 $('#video-content').innerHTML=`<div class="video-view-switch" role="group" aria-label="阅读或观看"><button class="play-button secondary" id="show-video-steps" aria-pressed="false">阅读大字步骤</button><button class="play-button secondary" id="show-video-player" aria-pressed="false">观看视频</button></div><section class="dialog-steps reader-steps" id="video-steps" tabindex="-1" hidden><h3>这几个动作，慢慢看</h3>${steps(v.steps.map((s,i)=>[`第${i+1}步`,s]))}<p class="micro-note">文字可随网页大字模式放大。需要看图解时，点上方“观看视频”。</p></section><div id="video-playback" hidden><div class="player-options" role="group" aria-label="选择播放来源"><button class="play-button" data-player-kind="local" aria-pressed="true">本站中文图解</button><button class="play-button secondary" data-player-kind="official" aria-pressed="false">官方真人视频 · YouTube</button></div><div class="player" id="care-player"></div><p class="dialog-language" id="player-description"></p><div id="video-state" class="video-state" role="status" hidden></div><div class="video-actions"><a href="${esc(mediaUrl(v.clipPath))}" download="${v.id}-中文图解.mp4">下载图解短片</a><a href="${esc(v.sourceUrl)}" target="_blank" rel="noopener noreferrer">官方中文页面／文字稿</a></div>${v.backupUrl?`<a class="backup-video" href="${esc(v.backupUrl)}" target="_blank" rel="noopener noreferrer">NHS英语真人示范（在官方页观看）</a>`:''}</div><p class="micro-note">本站图解由小小长大整理。${id==='diaper'?'步骤依据香港卫生署家庭健康服务；尿布图形为本站绘制。':'照片来源：香港卫生署家庭健康服务，按其非商业转载条款署名使用。'}原机构未制作或审核本站图解。</p>`;
 const showView=mode=>{const reading=mode==='steps';$('#video-steps').hidden=!reading;$('#video-playback').hidden=reading;$('#show-video-steps').setAttribute('aria-pressed',String(reading));$('#show-video-player').setAttribute('aria-pressed',String(!reading));if(reading){clearTimeout(videoFallbackTimer);$('#care-player').innerHTML='';}else playCareVideo(id,'local');$('#video-dialog').scrollTop=0;};
 $('#video-dialog').showModal();$('#show-video-steps').addEventListener('click',()=>showView('steps'));$('#show-video-player').addEventListener('click',()=>showView('video'));
 $$('#video-content [data-player-kind]').forEach(b=>b.addEventListener('click',()=>playCareVideo(id,b.dataset.playerKind)));
 showView(document.documentElement.classList.contains('large-type')?'steps':'video');
}

$('#video-close').addEventListener('click',()=>$('#video-dialog').close());$('#video-dialog').addEventListener('close',()=>{clearTimeout(videoFallbackTimer);$('#video-content').innerHTML='';lastVideoFocus?.focus({preventScroll:true})});$('#video-dialog').addEventListener('click',e=>{if(e.target===$('#video-dialog')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
addEventListener('message',e=>{if(e.origin!=='https://www.youtube-nocookie.com'||e.source!==$('#video-content iframe')?.contentWindow)return;let m=e.data;try{if(typeof m==='string')m=JSON.parse(m)}catch(_){return}if(m.event==='onError'){clearTimeout(videoFallbackTimer);showVideoHelp('此视频暂时无法播放，请改用中文步骤或备用入口。')}if(m.event==='onStateChange'&&m.info===1||m.event==='infoDelivery'&&m.info?.playerState===1){clearTimeout(videoFallbackTimer);if($('#video-state'))$('#video-state').hidden=true}});
function setFont(on){document.documentElement.classList.toggle('large-type',on);$('#font-toggle').setAttribute('aria-pressed',String(on));$('#font-toggle').textContent=on?'标准字':'大字';try{localStorage.setItem('little-days-large-type',String(on))}catch(e){}}
try{if(localStorage.getItem('little-days-large-type')==='true')setFont(true)}catch(e){}$('#font-toggle').addEventListener('click',()=>setFont(!document.documentElement.classList.contains('large-type')));
function announce(s){clearTimeout(noticeTimer);$('#status').textContent=s;noticeTimer=setTimeout(()=>$('#status').textContent='',7000)}
function offline(){const html=document.documentElement.cloneNode(true);if(!html.dataset.careMediaBase&&/^https?:$/.test(location.protocol))html.dataset.careMediaBase=new URL('.',location.href).href;html.querySelectorAll('dialog').forEach(d=>d.removeAttribute('open'));html.querySelector('#search-results').innerHTML='';html.querySelector('#search-status').textContent='';html.querySelector('#search-query').value='';html.querySelector('#home-query').value='';html.querySelector('#video-content').innerHTML='';html.querySelector('#status').textContent='';const blob=new Blob(['<!doctype html>\n'+html.outerHTML],{type:'text/html;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='小小长大-图文照护手册.html';a.click();setTimeout(()=>URL.revokeObjectURL(url),12000);announce('已发起下载。图文可离线查看；视频和外部资料仍需联网。')}
$('#offline').addEventListener('click',offline);$('#offline-bottom').addEventListener('click',offline);$('#print').addEventListener('click',()=>window.print());$('#print-bottom').addEventListener('click',()=>window.print());
let detailsBeforePrint=[];addEventListener('beforeprint',()=>{detailsBeforePrint=$$('details').map(d=>[d,d.open]);detailsBeforePrint.forEach(([d])=>d.open=true)});addEventListener('afterprint',()=>detailsBeforePrint.forEach(([d,o])=>d.open=o));
$('#source-list').innerHTML=`<div class="source-list">${Object.entries(SOURCE).map(([id,s])=>`<div id="source-${id}"><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></div>`).join('')}${Object.values(ASSETS).map(a=>`<div><a href="${esc(a.source)}" target="_blank" rel="noopener noreferrer">图片出处：${esc(a.title)}</a><small>香港卫生署家庭健康服务，原图完整呈现。依其非商业转载条款使用并署名。</small></div>`).join('')}</div>`;
document.querySelectorAll('a[href="#sources"],a[href="#source-redflags"]').forEach(a=>a.addEventListener('click',()=>$('#sources').open=true));
$('#medical').insertAdjacentHTML('beforeend',refs(['redflags','fever','jaundice','vomit']));
render(false);
if(location.hash==='#medical')requestAnimationFrame(()=>$('#medical').scrollIntoView());
